export const productData = [
  {
    id: 0,
    img: "/assets/images/new/product1.webp",
    imgBack: "/assets/images/new/product1.webp",
    name: "New",
    link: "/newin",
    addToCart: false,
  },
  {
    id: 1,
    img: "/assets/images/new/product2.webp",
    imgBack: "/assets/images/new/product2.webp",
    name: "Rain",
    link: "/rain",
    addToCart: false,
  },
  {
    id: 2,
    img: "/assets/images/new/product3.webp",
    imgBack: "/assets/images/new/product3.webp",
    name: "Snow",
    link: "/snow",
    addToCart: false,
  },
  {
    id: 3,
    img: "/assets/images/new/product4.webp",
    imgBack: "/assets/images/new/product4.webp",
    name: "All Weather",
    link: "/allweather",
    addToCart: false,
  },
];

export const allWeather = [
  {
    id: 0,
    img: "/assets/images/new/boot1.webp",
    imgBack: "/assets/images/new/boot1Back.webp",
    name: "The Modern Winter Boot in Beige",
    price: 2800,
    isSecond: false,
    desc: "Weekend Boot in Sage. Water Resistant. All Year. Rs. 2,800",
    addToCart: true,
  },
  {
    id: 1,
    img: "/assets/images/new/boot2.webp",
    imgBack: "/assets/images/new/boot2Back.webp",
    name: "The Modern Winter Boot in Black",
    price: 8000,
    isSecond: false,
    desc: "Weekend Boot in Sage. All Year. Water Resistant Rs. 8,000",
    addToCart: true,
  },
  {
    id: 2,
    img: "/assets/images/new/boot3.webp",
    imgBack: "/assets/images/new/boot3Back.webp",
    name: "Anybody Rain Boot In Sage",
    price: 1500,
    isSecond: false,
    desc: "Weekend Boot in Sage. All Year. Water Resistant Rs. 1,500",
    addToCart: true,
  },
  {
    id: 3,
    img: "/assets/images/new/boot4.webp",
    imgBack: "/assets/images/new/boot4Back.webp",
    name: "Anybody Rain Boot In Black",
    price: 5000,
    isSecond: true,
    desc: "Weekend Boot in Sage. All Year. Rs. 5,000",
    addToCart: true,
  },
  {
    id: 4,
    img: "/assets/images/new/boot5.webp",
    imgBack: "/assets/images/new/boot5Back.webp",
    name: "Anybody Rain Boot In Yellow",
    price: 5600,
    isSecond: true,
    desc: "Weekend Boot for Rain. All Year. Rs. 5,600",
    addToCart: true,
  },
  {
    id: 5,
    img: "/assets/images/new/boot6.webp",
    imgBack: "/assets/images/new/boot6Back.webp",
    name: "The Weekend Boot",
    price: 1000,
    isSecond: true,
    desc: "Modern Winter Boot in Black. All Year. Rs. 1,000",
    addToCart: true,
  },
  {
    id: 6,
    img: "/assets/images/new/boot7.webp",
    imgBack: "/assets/images/new/boot7Back.webp",
    name: "The Modern Winter Boot in Sage",
    price: 3000,
    isSecond: true,
    desc: "Modern Winter Boot in Black. All Year. Rs. 3,000",
    addToCart: true,
  },
  {
    id: 7,
    img: "/assets/images/new/boot2.webp",
    imgBack: "/assets/images/new/boot2Back.webp",
    name: "The Modern Boot in Black",
    price: 4000,
    isSecond: true,
    desc: "Modern Boot in Black. All Year. Rs. 4,000",
    addToCart: true,
  },
  {
    id: 8,
    img: "/assets/images/new/boot9.webp",
    imgBack: "/assets/images/new/boot9Back.webp",
    name: "The Weekend Boot Sage",
    price: 1000,
    isSecond: true,
    desc: "Weekend Boot in sage. All Year. Rs. 1,000",
    addToCart: true,
  },
  {
    id: 9,
    img: "/assets/images/new/boot10.webp",
    imgBack: "/assets/images/new/boot10Back.webp",
    name: "The Weekend Boot in Black",
    price: 5000,
    isSecond: true,
    desc: "Modern Boot in Black. All Year. Rs. 5,000",
    addToCart: true,
  },
  {
    id: 10,
    img: "/assets/images/new/boot11.webp",
    imgBack: "/assets/images/new/boot11Back.webp",
    name: "The New Classical Brown",
    price: 1000,
    isSecond: true,
    desc: "Modern Winter Clasical Boot. All Year. Rs. 1,000",
    addToCart: true,
  },
  {
    id: 11,
    img: "/assets/images/new/boot12.webp",
    imgBack: "/assets/images/new/boot12Back.webp",
    name: "The Modern Winter Boot in Sage",
    price: 5000,
    isSecond: true,
    desc: "Modern Winter Boot in Sage. All Year. Rs. 5,000",
    addToCart: true,
  },
];
